# Generated by Django 2.0.5 on 2018-07-02 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='CommentQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='PostQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=3000)),
                ('tags', models.CharField(max_length=200)),
                ('time', models.DateTimeField()),
                ('username', models.CharField(max_length=100)),
                ('viewcount', models.IntegerField()),
                ('votecount', models.IntegerField()),
                ('answercount', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TagQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('postquestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osqaapp.PostQuestion')),
            ],
        ),
        migrations.CreateModel(
            name='ViewQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postquestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osqaapp.PostQuestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ViewsCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('postquestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osqaapp.PostQuestion')),
            ],
        ),
        migrations.CreateModel(
            name='VoteQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postquestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osqaapp.PostQuestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VotesCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('postquestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osqaapp.PostQuestion')),
            ],
        ),
        migrations.AddField(
            model_name='commentquestion',
            name='postquestion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osqaapp.PostQuestion'),
        ),
        migrations.AddField(
            model_name='commentquestion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answerquestion',
            name='postquestion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osqaapp.PostQuestion'),
        ),
        migrations.AddField(
            model_name='answerquestion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
