# Generated by Django 2.0.5 on 2018-07-02 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osqaapp', '0002_auto_20180702_1053'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('postquestionid', models.CharField(max_length=1000)),
                ('count', models.IntegerField()),
            ],
        ),
    ]
