# Generated by Django 2.0.5 on 2018-07-06 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osqaapp', '0003_tagcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerquestion',
            name='time',
            field=models.DateTimeField(default='2018-07-02 10:55:06'),
        ),
        migrations.AddField(
            model_name='answerquestion',
            name='votecount',
            field=models.IntegerField(default=0),
        ),
    ]
